### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [12]:
import numpy as np
import random

In [34]:
# Option 1
vector_try = np.array([random.uniform(0,1) for _ in range(10)])
display(vector_try, vector_try.shape)

array([0.44384398, 0.78955932, 0.33304175, 0.97477866, 0.07023092,
       0.56806831, 0.18791479, 0.11208687, 0.19631486, 0.8617557 ])

(10,)

In [33]:
# Option 2
vector = np.random.rand(10)
display(vector, vector.shape)

array([4.72004155e-02, 3.46591486e-02, 6.43289839e-01, 3.25102773e-01,
       5.71893320e-01, 8.31047100e-01, 1.52378997e-05, 5.87049002e-03,
       4.94800411e-01, 9.16174085e-01])

(10,)

In [4]:
matrix = np.array([[11, 14, 17], [20, 23, 26], [29, 32, 35]])
display(matrix, matrix.shape)

array([[11, 14, 17],
       [20, 23, 26],
       [29, 32, 35]])

(3, 3)


### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [32]:
# 1
vector_plus_10 = np.round(vector + 10, 2)
display(vector_plus_10)
# 2
matrix_multiply_2 = matrix * 2
display(matrix_multiply_2)
# 3
new_vector_square = vector ** 2
display(new_vector_square)

array([10.58, 10.88, 10.14, 10.6 , 10.2 , 10.28, 10.33, 10.2 , 10.47,
       10.09])

array([[22, 28, 34],
       [40, 46, 52],
       [58, 64, 70]])

array([0.33651965, 0.78305784, 0.01882024, 0.35828746, 0.03941216,
       0.07774617, 0.10747325, 0.04140698, 0.21795999, 0.00805727])


### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 1х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [35]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [64]:
# 1
result_matrix = np.dot(B, A)
display(result_matrix, result_matrix.shape)
# 2
# В результаті перемноження матриці result_matrix та вектору C отримаємо  матрицю 2x1
# Для C * result_matrix буде помилка через неспівпадіння розмірності перемножуваних вектору С та матриці result_matrix
display(np.dot(result_matrix, C))
# 3
display(np.dot(D, result_matrix))

array([[0.7281, 0.5202],
       [0.2034, 0.2846]])

(2, 2)

array([[0.5202],
       [0.2846]])

array([[0.2034, 0.2846],
       [0.7281, 0.5202]])


### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [65]:
# 1
# Колонки стали строками, строки стали колонками
display(result_matrix.transpose())
# 2
# Форма структури вектору не змінилася, значення не змінилися
display(vector.shape)
display(vector.transpose().shape)
#3
# Форма структури вектору змінилась з одновимірного (10,) на одновимірний із віссю (10,1), те саме що 10 рядків та 1 колонка
column_vector = np.expand_dims(vector, axis=1)
display(vector, vector.shape)
display(column_vector, column_vector.shape)
#4
# Форма оригінального вектору (10,1). Форма транспонованого вектору (1,10)
display(column_vector.transpose(), column_vector.transpose().shape)

array([[0.7281, 0.2034],
       [0.5202, 0.2846]])

(10,)

(10,)

array([4.72004155e-02, 3.46591486e-02, 6.43289839e-01, 3.25102773e-01,
       5.71893320e-01, 8.31047100e-01, 1.52378997e-05, 5.87049002e-03,
       4.94800411e-01, 9.16174085e-01])

(10,)

array([[4.72004155e-02],
       [3.46591486e-02],
       [6.43289839e-01],
       [3.25102773e-01],
       [5.71893320e-01],
       [8.31047100e-01],
       [1.52378997e-05],
       [5.87049002e-03],
       [4.94800411e-01],
       [9.16174085e-01]])

(10, 1)

array([[4.72004155e-02, 3.46591486e-02, 6.43289839e-01, 3.25102773e-01,
        5.71893320e-01, 8.31047100e-01, 1.52378997e-05, 5.87049002e-03,
        4.94800411e-01, 9.16174085e-01]])

(1, 10)